# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go Modules dependencies
  - package-ecosystem: "gomod"
    directory: "/" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "abrakingoo"
      - "jesee-kuya"
      - "JoabOwala"
      - "johneliud"
      - "kh3rld"
      - "Tomlee-abila"
    labels:
      - "dependencies"
      - "go-modules"
    ignore:
      - dependency-name: "golang.org/x/*"
        versions: ["<1.21"] 

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci/cd"
