run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - goconst
    - gofmt
    - revive
    - staticcheck

issues:
  max-issues-per-linter: 10
  max-same-issues: 3
