version: 1.58.1

linters:

  enable:
    - bidichk
    - goimports
    - misspell
    - govet
    - errcheck
    - goconst
    - gofmt
    - revive
    - staticcheck
    - gocritic
    - unused
    - ineffassign
    - bodyclose

run:
  timeout: 5m
