name: Test Go

on:
  push:
    branches:
      - alpha
      - beta
      - dev
  pull_request:
    branches: [alpha, beta, dev, main]
    paths:
      - "cmd/**"

jobs:
  test:
    name: Go Tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-22.04, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: Test All
        working-directory: ./cmd
        run: |
          files=$(go list ./...)
          SAVEIFS=$IFS
          IFS=$'\n'
          file_arr=($files)
          IFS=$SAVEIFS

          for (( i=0; i<${#file_arr[@]}; i++ ))
          do
            echo "Testing Package: ${file_arr[$i]}"
            if [ "$MATRIX_OS" == 'ubuntu-22.04' ]
            then
              if [[ "${file_arr[$i]}" != *enginetest* ]]; then
                go test -vet=off -timeout 45m -race "${file_arr[$i]}"
              else
                echo "skipping enginetests for -race"
              fi
            else
              go test -vet=off -timeout 45m "${file_arr[$i]}"
            fi
            succeeded=$(echo "$?")
            if [ "$succeeded" -ne 0 ]; then
              echo "Testing failed in package ${file_arr[$i]}"
              exit 1;
            fi
          done
        env:
          MATRIX_OS: ${{ matrix.os }}
