name: Build && Test

on:
  push:
    branches:
    - alpha
    - beta
    - dev
    - main
  pull_request:
    branches:
    - alpha
    - beta
    - dev
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Init
      run: go mod init github.com/Zone01-Kisumu-Open-Source-Projects/kisumu-lang 
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
